### ISSUE TITLE
Portuguese Translation

### ISSUE THREAD

**Issue by rthrash** [modxcms/fred#122]
We're looking for someone to volunteer to translate Fred into Portuguese. We are now using Crowdin to do so: https://crowdin.com/project/fred

Please let us know if you're able to participate and we'll stub ou the language to get started.

Thanks!

**Comment by rthrash** [comment]
We have added it to Crowdin: https://crowdin.com/project/fred/pt-BR#

Thanks for volunteering!

**Comment by rthrash** [comment]
Hi @tekpixo, have you been able to look at the Crowdin project for this yet?

**Comment by JANogueira** [comment]
Hi Ryan,

Please consider changing this to Portuguese only.

Why?
There is an "orthographic agreement" for all countries with Portuguese as primary native language.
The objective of this agreement is to have all countries writing on the same way.

So I believe that there is little sense to talk about Portuguese from Portugal or Portuguese from Brazil (or Angola, or Mozambique, etc).

Please consider changing this to "Portuguese".
I am also willing to help with this translation.
Portuguese is my native language.

Please share your thoughts.
Thanks.
Cheers all

**Comment by theboxer** [comment]
Done, thank you for the info

**Comment by JANogueira** [comment]
Many thanks,

@rthrash can you please also change the title of this thread?
As soon as I have been accepted on crowdin, I will start the translation. I will try to be as generic as possible trying to avoid expressions that can be typically from Portugal as there are some relevant semantic differences from Portugal and Brazil (as an example).

I am open to suggestions from Brazil folks in case I am using something less generic expressions.
Cheers all

**Comment by theboxer** [comment]
Title changed and I think I just approved you in crowdin ;)

**Comment by JANogueira** [comment]
Thanks John. Yes, I am there already.
I will start with some translations today. I am still getting used to the interface.

Cheers and many thanks once again.

**Comment by theboxer** [comment]
Awesome, thank you!

**Comment by JANogueira** [comment]
Hi All,

Portuguese translation is ready.
I tried to dig into the Fred code to understand if the context of some more generic texts placement would make sense. This way the translations can be more consistent.

Please tag me if you need additional checks/revisions or new translations.

Cheers
